theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
apply_source_formatting : true
force_p_newlines : false
force_br_newlines : true
convert_newlines_to_brs : false
remove_linebreaks : true
forced_root_block : 0
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
  - code
plugins:
  - table
  - fullscreen
  - code